title: My IT Learning Journey
description: Documenting my path through DevOps, Docker, Kubernetes, and CI/CD
author: Frog Catcher
email: frog.catcher@example.com

# Theme
theme: minima
skin: dark

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Social links (optional)
github_username: yourusername
linkedin_username: yourlinkedin

# Show excerpts on home page
 show_excerpts: false
